const LABELS = { premier:'Bプレミア', one:'Bワン', next:'Bネクスト' };
const state = { league:'premier', dataByLeague:new Map(), data:null, dates:[], selectedDates:{}, selectedDate:null, tab:'standings', updating:false, token:0 };
const $ = (s) => document.querySelector(s);
const esc = (v) => String(v ?? '—').replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today = () => new Intl.DateTimeFormat('en-CA', { timeZone:'Asia/Tokyo' }).format(new Date());
const dateLabel = (d) => { if (!d) return '2026-27シーズン'; const [y,m,day]=d.split('-'); return `${y}年${Number(m)}月${Number(day)}日`; };
const weekday = (d) => new Intl.DateTimeFormat('ja-JP', { weekday:'short', timeZone:'Asia/Tokyo' }).format(new Date(`${d}T00:00:00+09:00`));
const updateText = (v) => v ? new Intl.DateTimeFormat('ja-JP',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Tokyo'}).format(new Date(v)) : '';
function status(update={}) { const fail=update.status==='failure'; $('#status-indicator').className=`status-indicator ${update.status||''}`; $('#status-label').textContent=fail?'更新失敗':update.status==='success'?'更新済み':'読み込み中'; $('#status-detail').textContent=fail?(update.message||'前回正常に取得したデータを表示しています'):`${LABELS[state.league]}のデータを表示しています`; $('#updated-at').textContent=updateText(update.at); }
function selectDate(date, scroll=true) { state.selectedDate=date; state.selectedDates[state.league]=date; $('#selected-date').textContent=dateLabel(date); document.querySelectorAll('#date-nav .date-chip').forEach((b)=>b.classList.toggle('active',b.dataset.date===date)); const panel=$(`#match-days [data-date="${date}"]`); if(panel&&scroll) $('#match-days').scrollTo({left:panel.offsetLeft,behavior:'smooth'}); }
function renderDates(dates) { state.dates=dates; const selected=state.selectedDates[state.league]&&dates.includes(state.selectedDates[state.league])?state.selectedDates[state.league]:dates.find((d)=>d>=today())||dates.at(-1)||null; $('#date-nav').innerHTML=dates.map((d)=>{const x=new Date(`${d}T00:00:00+09:00`);return `<button class="date-chip${d===selected?' active':''}" type="button" data-date="${d}"><small>${x.getMonth()+1}月</small><strong>${x.getDate()}</strong><span>${weekday(d)}</span></button>`}).join(''); document.querySelectorAll('#date-nav .date-chip').forEach((b)=>b.addEventListener('click',()=>selectDate(b.dataset.date))); selectDate(selected,false); }
function renderMatches(matches=[]) { const by=new Map(); matches.forEach((m)=>{if(!by.has(m.date))by.set(m.date,[]);by.get(m.date).push(m)}); const dates=[...by.keys()].sort(); renderDates(dates); const root=$('#match-days'); root.innerHTML=dates.map((d)=>`<article class="match-day" data-date="${d}"><div class="match-list">${by.get(d).sort((a,b)=>(a.kickoff||'').localeCompare(b.kickoff||'')).map((m)=>{const done=m.status==='finished';const hw=done&&Number(m.homeScore)>Number(m.awayScore),aw=done&&Number(m.awayScore)>Number(m.homeScore);const label=m.status==='postponed'?'延期':m.status==='cancelled'?'中止':done?'試合終了':m.kickoff||'時刻未定';return `<div class="match-card"><div class="match-meta"><span>${esc(m.competition||'レギュラーシーズン')}${m.matchday?`・第${esc(m.matchday)}節`:''}</span><span class="${done?'match-time':'match-state'}">${esc(label)}</span></div><div class="scoreline"><div class="team-row home ${hw?'winner':aw?'loser':''}"><div class="team-name-block"><span class="team-side-label">Home</span><span class="team-name">${esc(m.home?.short)}</span></div><span class="score${done?'':' score-placeholder'}">${done?esc(m.homeScore):'0'}</span></div><span class="score-divider">—</span><div class="team-row away ${aw?'winner':hw?'loser':''}"><span class="score${done?'':' score-placeholder'}">${done?esc(m.awayScore):'0'}</span><div class="team-name-block"><span class="team-side-label">Away</span><span class="team-name">${esc(m.away?.short)}</span></div></div></div>${m.venue?`<div class="match-meta"><span>${esc(m.venue)}</span></div>`:''}</div>`}).join('')}</div></article>`).join(''); $('#empty-state').hidden=dates.length>0; if(!dates.length){$('#empty-state').textContent=state.data?'このカテゴリーの試合予定はありません':'データを取得できていません';$('#empty-state').hidden=false;} requestAnimationFrame(()=>{selectDate(state.selectedDate,false);const p=$(`#match-days [data-date="${state.selectedDate}"]`);if(p)$('#match-days').scrollTo({left:p.offsetLeft})}); }
function table(rows, title) { if(!rows?.length)return `<p class="b-note">${esc(title)}の順位情報は公式未発表です。</p>`; return `<h3>${esc(title)}</h3><div class="table-wrap" tabindex="0" aria-label="${esc(title)}順位表"><table class="b-zone-table"><thead><tr><th>順位</th><th class="team-column">クラブ</th><th>勝</th><th>負</th><th>勝率</th><th>差</th><th>試合数</th><th>残試合</th></tr></thead><tbody>${rows.map((r)=>`<tr><td>${esc(r.rank)}</td><td class="team-column">${esc(r.team)}</td><td>${esc(r.wins)}</td><td>${esc(r.losses)}</td><td>${esc(r.winPercentage)}</td><td>${esc(r.gamesBehind)}</td><td>${esc(r.played)}</td><td>${esc(r.remaining)}</td></tr>`).join('')}</tbody></table></div>`; }
function renderModal() { const content=$('#modal-content'); const st=state.data?.standings||{}; if(state.tab==='standings') content.innerHTML=(st.zones||[]).map((z)=>table(z.rows,z.name)).join('')||'<p class="b-note">順位表を取得できていません。</p>'; else if(state.tab==='wildcard') content.innerHTML=state.league==='next'?'<p class="b-note">Bネクストにはワイルドカード制度はありません。</p>':table(st.wildcard,'ワイルドカード順位'); else {const post=state.data?.postseason; content.innerHTML=post?.rounds?.length?post.rounds.map((r)=>`<div class="b-playoff-card"><strong>${esc(r.name)}</strong><span>${esc(r.home)} — ${esc(r.away)}　${esc(r.score||'予定')}</span></div>`).join(''):`<p class="b-note">${post?.status==='unavailable'?'プレーオフの公式情報は未取得です。':'プレーオフの日程は公式未発表です。'}</p>`;} }
function render(data) { state.data=data; state.dataByLeague.set(state.league,data); status(data.update); renderMatches(data.matches||[]); if(!$('#standings-sheet').hidden)renderModal(); document.title=`スポーツポータル | 2026-27 ${LABELS[state.league]}`; $('#league-panel').setAttribute('aria-label',`${LABELS[state.league]}の試合日程・結果`); }
async function load(league, force=false) { state.league=league; const cached=state.dataByLeague.get(league); if(cached&&!force){render(cached);return;} const token=++state.token; status({}); $('#empty-state').hidden=false; $('#empty-state').textContent='データを読み込んでいます'; try{const r=await fetch(`/api/b-league/data?league=${league}`,{headers:{Accept:'application/json'}});if(!r.ok)throw Error('データの読み込みに失敗しました');const data=await r.json();if(token!==state.token)return;render(data);}catch(e){if(token!==state.token)return;status({status:'failure',message:e.message});$('#empty-state').hidden=false;$('#empty-state').textContent='データを取得できませんでした';} }
async function refresh(){if(state.updating||!confirm(`${LABELS[state.league]}の試合予定・結果・順位を更新します。よろしいですか？`))return;state.updating=true;const league=state.league;status({status:'success',message:'公式サイトからデータを取得しています'});$('#refresh-button').disabled=true;try{const r=await fetch(`/api/b-league/update?league=${league}`,{method:'POST',headers:{Accept:'application/json'}});const x=await r.json();if(!r.ok)throw Error(x.error||'更新に失敗しました');render(x.data);}catch(e){status({status:'failure',message:e.message})}finally{state.updating=false;$('#refresh-button').disabled=false;} }
function openModal(){const s=$('#standings-sheet');s.hidden=false;s.setAttribute('aria-hidden','false');requestAnimationFrame(()=>s.classList.add('is-open'));$('#standings-button').setAttribute('aria-expanded','true');$('#standings-icon').textContent='×';$('#standings-label').textContent='閉じる';$('#standings-panel').focus();renderModal();}
function closeModal(){const s=$('#standings-sheet');s.classList.remove('is-open');s.setAttribute('aria-hidden','true');$('#standings-button').setAttribute('aria-expanded','false');$('#standings-icon').textContent='▦';$('#standings-label').textContent='順位';setTimeout(()=>{s.hidden=true},360);}
document.querySelectorAll('.league-tab').forEach((b)=>b.addEventListener('click',()=>{document.querySelectorAll('.league-tab').forEach((x)=>{x.classList.toggle('active',x===b);x.setAttribute('aria-selected',x===b?'true':'false')});load(b.dataset.league);})); document.querySelectorAll('.b-modal-tab').forEach((b)=>b.addEventListener('click',()=>{state.tab=b.dataset.modalTab;document.querySelectorAll('.b-modal-tab').forEach((x)=>{x.classList.toggle('active',x===b);x.setAttribute('aria-selected',x===b?'true':'false')});renderModal();})); $('#refresh-button').addEventListener('click',refresh);$('#standings-button').addEventListener('click',()=>$('#standings-sheet').hidden?openModal():closeModal());$('#standings-backdrop').addEventListener('click',closeModal);document.addEventListener('keydown',(e)=>{if(e.key==='Escape')closeModal();}); $('#match-days').addEventListener('scroll',()=>{const root=$('#match-days');if(!root.children.length)return;const date=[...root.children].reduce((best,c)=>Math.abs(c.offsetLeft-root.scrollLeft)<Math.abs(best.offsetLeft-root.scrollLeft)?c:best,root.children[0]);if(date&&date.dataset.date!==state.selectedDate)selectDate(date.dataset.date,false)}); load('premier');
